// @flow

export const FixMeActions = Object.freeze({
  CREATE: 'FIXME:CREATE',
  REMOVE: 'FIXME:REMOVE',
  ADD_COMMENT: 'FIXME:ADD_COMMENT',
  REMOVE_COMMENT: 'FIXME:REMOVE_COMMENT',
  VALIDATE_COMMENT: 'FIXME:VALIDATE_COMMENT'
});
