// @flow

export const SpecActions = Object.freeze({
  CREATE_PROJECT: 'SPEC:CREATE_PROJECT',
  REMOVE_PROJECT: 'SPEC:REMOVE_PROJECT',
  RENAME_PROJECT: 'SPEC:RENAME_PROJECT',
  SET_CONTENT: 'SPEC:SET_CONTENT'
});
